name: Simple Example

on:
  workflow_call:
    inputs:
      project_name:
        required: true
        type: string

jobs:
  CI_Steps:

    runs-on: [self-hosted]
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Code Lint
        run: echo "Ok"

      - name: Code Build
        run: echo "Ok"

      - name: Install nodejs module
        run: npm install



      - name: Code Unit Test
        run: echo npm runtest:unit

      - name: Code integration Test
        run: echo npm runtest:integration

      - name: Code Review
        run:  echo /opt/sonar-scanner-5.0.1.3006-linux/bin/sonar-scanner -Dsonar.host.url=http://sonarqube-internal.awsdevops16297.sbs:9000 -Dsonar.login=admin -Dsonar.password=DevOps321


      - name: Release software
        run: echo "Ok"



