name:  Release - Reusable
on:
  workflow_call:
    inputs:
      project_name:
        required: true
        type: string
      npm_install:
        required: true
        type: boolean
      release_archive_file:
        required: true
        type: string
    secrets:
      vault_token:
        required: true

jobs:
  CI_Steps:
    runs-on: [self-hosted]

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Install NodeJS modules
        run: npm install
        if: ${{ inputs.npm_install }}

      - name: Import secrets from Vault
        uses: hashicorp/vault-action@v2
        id: vault-secrets
        with:
          url: http://vault.awsdevops16297.sbs:8200/
          token: ${{ secrets.vault_token }}
          tlsSkipVerify: true
          secrets: |
            common/data/common artifactory_user | artifactory_user ;
            common/data/common artifactory_password | artifactory_password;

      -  name: Create Version File
         run: echo ${GITHUB_REF_NAME} >VERSION


      - name: Prepare artifact
        run: |
          sudo dnf install -y zip
          zip -r ${GITHUB_REF_NAME}.zip ${{ inputs.release_archive_file }}

      -  name: upload artifact to artifactory
         run: curl -f -v -u${{ steps.vault-secrets.outputs.artifactory_user}}:${{ steps.vault-secrets.outputs.artifactory_password}} -T ${GITHUB_REF_NAME}.zip "http://artifactory-internal.awsdevops16297.sbs:8081/artifactory/${{ inputs.project_name }}/${GITHUB_REF_NAME}.zip"
         #run: curl -f -v --user ${{ steps.vault-secrets.outputs.artifactory_user }}:${{ steps.vault-secrets.outputs.artifactory_password }} --data-binary @${GITHUB_REF_NAME}.zip -X PUT "http://artifactory-internal.awsdevops16297.sbs:8081/artifactory/${{ inputs.project_name }}/${GITHUB_REF_NAME}.zip"
      -  name: Trigger GoCD pipeline
         run: |
           echo '{
             "environment_variables": [
               {
                 "name": "App_VERSION",
                 "secure": false,
                 "value": "app_version"
               }
             ],
             "update_materials_before_scheduling": true
           }' | sed -e "s/app_version/${GITHUB_REF_NAME}/" | jq > data.json

           curl "http://172.31.67.92:8153/go/api/pipelines/${{ inputs.project_name }}/schedule" \
             -H "Accept: application/vnd.go.cd.v1+json" \
             -H "Content-Type: application/json" \
             -X POST \
             -d "@data.json"  




